version: '3'
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - UMASK_SET=022 #optional
    volumes:
      - /sonarr/config:/config
      - /mnt/nas/Tv \Shows:/tv
      - /mnt/nas/Downloads/nzb:/downloadsnzb
      - /mnt/nas/Downloads/Complete:/downloadstor
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
      image: linuxserver/radarr
      container_name: radarr
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=America/Chicago
        - UMASK_SET=022 #optional
      volumes:
        - /docker/sonarr/config:/config
        - /mnt/nas/Movies:/movies
        - /mnt/nas/Downloads/nzb:/downloadsnzb
        - /mnt/nas/Downloads/Complete:/downloadstor
      ports:
        - 7878:7878
      restart: unless-stopped

  lidarr:
      image: linuxserver/lidarr
      container_name: lidarr
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=America/Chicago
        - UMASK_SET=022 #optional
      volumes:
        - /docker/sonarr/config:/config
        - /mnt/nas/Music:/music
        - /mnt/nas/Downloads/nzb:/downloadsnzb
        - /mnt/nas/Downloads/Complete:/downloadstor
      ports:
        - 8686:8686
      restart: unless-stopped
      
        jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - RUN_OPTS=run options here #optional
    volumes:
      - /docker/sonarr/config:/config
      - /mnt/nas/Downloads/:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
