version: '3'
services:
  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - UMASK_SET=022 #optional
    volumes:
      - /docker/sonarr/config:/config
      - "/mnt/nas/TV\ Shows/:/tv"
      - /mnt/nas/Downloads/nzb/:/downloadsnzb
      - /mnt/nas/Downloads/Complete/:/downloadstor
    network_mode: DockerInternal
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
      image: ghcr.io/linuxserver/radarr:latest
      container_name: radarr
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=America/Chicago
        - UMASK_SET=022 #optional
      volumes:
        - /docker/radarr/config:/config
        - /mnt/nas/Movies/:/movies
        - /mnt/nas/Downloads/nzb:/downloadsnzb
        - /mnt/nas/Downloads/Complete:/downloadstor
      network_mode: DockerInternal
      ports:
        - 7878:7878
      restart: unless-stopped

  lidarr:
      image: ghcr.io/linuxserver/lidarr:latest
      container_name: lidarr
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=America/Chicago
        - UMASK_SET=022 #optional
      volumes:
        - /docker/lidarr/config:/config
        - /mnt/nas/Music:/music
        - /mnt/nas/Downloads/nzb:/downloadsnzb
        - /mnt/nas/Downloads/Complete:/downloadstor
      network_mode: DockerInternal
      ports:
        - 8686:8686
      restart: unless-stopped
      
  jackett:
    image: ghcr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - RUN_OPTS=run options here #optional
    volumes:
      - /docker/jackett/config:/config
      - /mnt/nas/Downloads/:/downloads
    network_mode: DockerInternal
    ports:
      - 9117:9117
    restart: unless-stopped

#  mylar:
#    image: ghcr.io/linuxserver/mylar
#    container_name: mylar
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=America/Chicago
#    volumes:
#      - /docker/mylar/config:/config
#      - /mnt/nas/Library/Comics:/comics
#      - /mnt/nas/Downloads/nzb:/downloadsnzb
#      - /mnt/nas/Downloads/Complete:/downloadstor
#    network_mode: DockerInternal
#    ports:
#      - 8090:8090
#    restart: unless-stopped

#  readarr:
#    image: hotio/readarr:unstable
#    container_name: readarr
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=America/Chicago
#    volumes:
#      - /docker/readarr/config:/config
#      - /mnt/nas/Library/:/library
#      - /mnt/nas/Downloads/nzb:/downloadsnzb
#      - /mnt/nas/Downloads/Complete:/downloadstor
#    network_mode: DockerInternal
#    ports:
#      - 8787:8787
#    restart: unless-stopped

  lazylibrarian:
    image: ghcr.io/linuxserver/lazylibrarian:latest
    container_name: lazylibrarian
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - DOCKER_MODS=linuxserver/calibre-web:calibre #optional
    volumes:
      - /docker/lazylibrarian/config:/config
      - /mnt/nas/Library/:/library
      - /mnt/nas/Downloads/nzb/nzb:/watch
      - /mnt/nas/Downloads/nzb:/downloadsnzb
      - /mnt/nas/Downloads/Complete:/downloadstor
    network_mode: DockerInternal
    ports:
      - 5299:5299
    restart: unless-stopped
