version: '3'
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - UMASK_SET=022 #optional
    volumes:
      - /docker/sonarr/config:/config
      - "/mnt/nas/TV\ Shows/:/tv"
      - /mnt/nas/Downloads/nzb/:/downloadsnzb
      - /mnt/nas/Downloads/Complete/:/downloadstor
    network_mode: DockerInternal
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
      image: linuxserver/radarr
      container_name: radarr
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=America/Chicago
        - UMASK_SET=022 #optional
      volumes:
        - /docker/radarr/config:/config
        - /mnt/nas/Movies/:/movies
        - /mnt/nas/Downloads/nzb:/downloadsnzb
        - /mnt/nas/Downloads/Complete:/downloadstor
      network_mode: DockerInternal
      ports:
        - 7878:7878
      restart: unless-stopped

  lidarr:
      image: linuxserver/lidarr
      container_name: lidarr
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=America/Chicago
        - UMASK_SET=022 #optional
      volumes:
        - /docker/lidarr/config:/config
        - /mnt/nas/Music:/music
        - /mnt/nas/Downloads/nzb:/downloadsnzb
        - /mnt/nas/Downloads/Complete:/downloadstor
      network_mode: DockerInternal
      ports:
        - 8686:8686
      restart: unless-stopped
      
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - RUN_OPTS=run options here #optional
    volumes:
      - /docker/jackett/config:/config
      - /mnt/nas/Downloads/:/downloads
    network_mode: DockerInternal
    ports:
      - 9117:9117
    restart: unless-stopped

  mylar:
    image: linuxserver/mylar
    container_name: mylar
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /docker/mylar/config:/config
      - /mnt/nas/Library/Comics:/comics
      - /mnt/nas/Downloads/nzb:/downloadsnzb
      - /mnt/nas/Downloads/Complete:/downloadstor
    network_mode: DockerInternal
    ports:
      - 8090:8090
    restart: unless-stopped

  readarr:
    image: hotio/readarr
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /docker/mylar/config:/config
      - /mnt/nas/Library/:/library
      - /mnt/nas/Downloads/nzb:/downloadsnzb
      - /mnt/nas/Downloads/Complete:/downloadstor
    network_mode: DockerInternal
    ports:
      - 8787:8787
    restart: unless-stopped