services:
  tautulli:
    image: lscr.io/linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 1m
    volumes:
      - /docker/tautulli:/config
      - /docker/tautulli/logs:/logs
      - /mnt/nas/:/nas
    network_mode: DockerInternal
    ports:
      - 8181:8181
    restart: unless-stopped
