services:
  CodeProjectAI:
    image: codeproject/ai-server
    container_name: codeproject-ai-server-cpu
    hostname: codeproject-ai-server
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 1m
    ports:
      - "32168:32168"
    environment:
      - TZ=America/Chicago
    volumes:
      - /docker/codeprojectai/etc:/etc/codeproject/ai
      - /docker/codeprojectai/opt:/app/modules
