# docker-compose.yml
version: '3'
services:
  ombi:
    image: lscr.io/linuxserver/ombi:latest
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    #network_mode: DockerInternal  
    #ports:
    #  - 80:3579
    volumes:
      - /docker/ombi/config:/config
      #- /docker/ssh/acme:/ssl
    labels:
      - traefik.enable=true
      - traefik.http.routers.ombi.rule=Host(`ombi.tuckeredoutbert.com`)  
      - traefik.http.routers.ombi.entrypoints=web-secure
      - traefik.http.routers.ombi.tls.certresolver=lets-encrypt
      - traefik.docker.network=DockerExternal
    networks:
      DockerExternal:
      DockerInternal:
    #network_mode: DockerInternal
    #ports:
    #  - 8011:8080
    restart: unless-stopped
networks:
  DockerExternal:
    external: true
  DockerInternal:
    external: true
