# docker-compose.yml
version: '3'
services:
  ombi:
    image: lscr.io/linuxserver/ombi:latest
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 1m
    volumes:
      - /docker/ombi/config:/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.ombi.rule=Host(`ombi.tuckeredoutbert.com`)  
      - traefik.http.routers.ombi.entrypoints=web-secure
      - traefik.http.routers.ombi.tls.certresolver=lets-encrypt
      - traefik.docker.network=DockerExternal
    networks:
      DockerExternal:
      DockerInternal:
    restart: unless-stopped
networks:
  DockerExternal:
    external: true
  DockerInternal:
    external: true
