version: '3.8'

services:
  camera.ui:
    container_name: camera.ui
    image: nexryai/camera.ui:latest
    logging:
       driver: "json-file"
       options:
          max-file: 5
          max-size: 1m
    ports:
     - "8081:8081"
     - "1883:1883"
     - "7272:7272"
    volumes:
      - /docker/camera.ui/config:/.camera.ui:rw
    network_mode: DockerInternal
    restart: unless-stopped
