version: "3.7"
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 13378:13378
    volumes:
      - '/mnt/nas/Library/Audio\ Books':/audiobooks
      - /mnt/nas/Library/podcasts:/podcasts
      - /mnt/nas/audiobookshelf/config:/config
      - /mnt/nas/audiobookshelf/metadata:/metadata
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 1m
    networks:
      DockerExternal:
      DockerInternal:
    restart: unless-stopped
    
networks:
  DockerExternal:
    external: true
  DockerInternal:
    external: true
