services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    ports:
      - 13378:80
    volumes:
      - /mnt/nas/Library/audiobooks:/audiobooks
      - /mnt/nas/Library/books:/enooks
      - /docker/audiobookshelf/config:/config
      - /mnt/nas/bk/audiobookshelf/metadata:/metadata
    environment:
      - TZ=America/Chicago
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 1m
    labels:
      - traefik.enable=true
      - traefik.http.routers.audiobookshelf.rule=Host(`library.tuckeredoutbert.com`)  
      - traefik.http.routers.audiobookshelf.entrypoints=web-secure
      - traefik.http.routers.audiobookshelf.tls.certresolver=lets-encrypt
      - traefik.docker.network=DockerExternal
    networks:
      DockerExternal:
      DockerInternal:
    restart: unless-stopped
networks:
  DockerExternal:
    external: true
  DockerInternal:
    external: true
