services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 1m
    volumes:
      - /docker/heimdall/config:/config
    network_mode: DockerInternal
    ports:
      - 4480:80
      - 9443:443
    restart: unless-stopped
