services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /docker/heimdall/config:/config
    ports:
      - 4480:80
      - 9443:443
    restart: unless-stopped
