version: "3"
services:
  muximux:
    image: ghcr.io/linuxserver/muximux
    container_name: muximux
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /docker/muximux/config:/config
    network_mode: DockerInternal
    ports:
      - 1180:80
      - 1443:443
    restart: unless-stopped
