
version: "2.1"
services:
  komga:
    image: gotson/komga
    container_name: komga
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - JAVA_TOOL_OPTIONS=-Xmx1g
    volumes:
      - /docker/komga/config:/config
      - /mnt/nas/Library/Comics:/comics
    label:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`komga.tuckeredoutbert.com`)  
      - traefik.http.routers.whoami.entrypoints=web-secure
      - traefik.http.routers.whoami.tls.certresolver=lets-encrypt
      - traefik.docker.network=DockerExternal
    #networks:
    #  DockerExternal:
    network_mode: 
      - DockerInternal
      - DockerExternal
    #ports:
    #  - 8011:8080
    restart: unless-stopped
