
version: "2.1"
services:
  komga:
    image: gotson/komga
    container_name: komga
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - JAVA_TOOL_OPTIONS=-Xmx1g
    volumes:
      - /docker/komga/config:/config
      - /mnt/nas/Library/Comics:/comics
    labels:
      - traefik.enable=true
      - traefik.http.routers.komga.rule=Host(`komga.tuckeredoutbert.com`)  
      - traefik.http.routers.komga.entrypoints=web-secure
      - traefik.http.routers.komga.tls.certresolver=lets-encrypt
      - traefik.docker.network=DockerExternal
    networks:
      DockerExternal:
      DockerInternal:
    #network_mode: DockerInternal
    #ports:
    #  - 8011:8080
    restart: unless-stopped
