services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      #- UMASK_SET=022 #optional
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 1m
    volumes:
      - /docker/sabnazbd/config:/config
      - /mnt/nas/Downloads/nzb:/downloads #optional
      - /mnt/nas/Downloads/nzb/intermediate:/incomplete-downloads #optional
      - /mnt/nas/bk/sabnzbd:/backup
    network_mode: DockerInternal
    ports:
      - 8080:8080
    restart: unless-stopped 
