services:
  sftp:
    image: atmoz/sftp
    container_name: sftp
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 1m
    restart: unless-stopped
    network_mode: DockerInternal
    cap_add:
      - SYS_ADMIN
    ports:
      - "9922:22"
    volumes:
      - /docker/sftp/data:/home
      - /mnt/nas/upload:/upload
      - "/mnt/nas/TV\ Shows/:/tv"
      - /mnt/nas/Movies/:/movies
      - /mnt/nas/Library:/library
      - /docker/sftp/users.conf:/etc/sftp/users.conf
      - /docker/sftp/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key:ro
      - /docker/sftp/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key:ro
      - /docker/sftp/bindmount.sh:/etc/sftp.d/bindmount.sh
