services:
 sftp:
    image: atmoz/sftp
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 1m
    restart: unless-stopped
    network_mode: DockerInternal
    ports:
        - "22:9922"       
    volumes:
      - /mnt/nas/upload:/home/upload
      - /docker/sftp/users.conf:/etc/sftp/users.conf:ro \
      - /docker/sftp/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key:ro
      - /docker/sftp/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key:ro
