services:
 sftp:
    image: atmoz/sftp
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 1m
    restart: unless-stopped
    network_mode: DockerInternal
    ports:
        - "9922:22"       
    volumes:
      - /mnt/nas/upload:/home/$user/upload
      - "/mnt/nas/TV Shows":/home/tv:ro
      - /mnt/nas/Movies:/home/movies:ro
      - /mnt/nas/Library:/home/library:ro
      - /docker/sftp/users.conf:/etc/sftp/users.conf
      - /docker/sftp/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key:ro
      - /docker/sftp/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key:ro
