version: '3.5'
services:
  sftptest:
    image: atmoz/sftp
    container_name: sftp
    restart: unless-stopped
    network_mode: DockerInternal
    volumes:
      - /Docker-Compose/sftp/users.conf:/etc/sftp/users.conf:ro
      - /Docker-Compose/sftp/scripts/:/etc/sftp.d/
      - /mnt/nas/:/home
      - /docker/ssh/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key
      - /docker/ssh/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key
    ports:
      - "9922:22"