services:
  traefik:
    image: traefik:latest
    container_name: traefik
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 1m
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /docker/Traefik/traefik.yml:/etc/traefik/traefik.yml
      - /docker/Traefik/acme.json:/acme.json
      - /docker/Traefik/letsencrypt:/letsencrypt
      - /docker/Traefik/logs:/logs
    labels:
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.rule=Host(`traefik.tuckeredoutbert.com`)
      - traefik.http.routers.traefik.tls.certresolver=lets-encrypt
      - traefik.http.routers.traefik.tls.domains.main=tuckeredoutbert.com
      - traefik.http.routers.traefik.tls.domains.sans=*.tuckeredoutbert.com,tuckeredoutbert.com
      - traefik.http.routers.traefik.entrypoints=web-secure
      - traefik.docker.network=DockerExternal
    env_file: /mnt/nas/bk/Traefik/traefik.env  
    networks:
      DockerExternal:
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped 
networks:
  DockerExternal:
    external: true
