version: '3.5'
services:
  traefik:
    image: "traefik:v2.6.2"
    container_name: traefik
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/nas/bk/Traefik/traefik.yml:/etc/traefik/traefik.yml
      - /mnt/nas/bk/Traefik/acme.json:/acme.json
      - /mnt/nas/bk/Traefik/letsencrypt:/letsencrypt
      - /mnt/nas/bk/Traefik/logs:/logs
    network_mode: DockerExternal
    labels:
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.rule=Host(`traefik.tuckeredoutbert.com` || 'traefik')
      - traefik.http.routers.traefik.tls.certresolver=lets-encrypt
      - traefik.http.routers.traefik.tls.domains[0].main=tuckeredoutbert.com
      - traefik.http.routers.traefik.tls.domains[0].sans=*.tuckeredoutbert.com,turkeredoutbert.com
      - traefik.http.routers.traefik.entrypoints=web-secure
      - traefik.docker.network=DockerExternal
    env_file: /mnt/nas/bk/Traefik/traefik.env  
    networks:
      DockerExternal:
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped 
networks:
  DockerExternal:
    external: true
