version: '3'
services:
  traefik:
    image: traefik:v2.2
    container_name: traefik
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/nas/bk/Traefik/traefik.toml:/traefik.toml
      - /mnt/nas/bk/Traefik/traefik_dynamic.toml:/traefik_dynamic.toml
      - /mnt/nas/bk/Traefik/acme.json:/acme.json
    network_mode: web
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped 
