version: "2.1"
services:
  calibre:
    image: linuxserver/calibre
    container_name: calibre
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - UMASK_SET=022 #optional
      - CLI_ARGS= #optional
    volumes:
      - /docker/calibre/config:/config
      - /mnt/nas/Library/Books:/books
    network_mode: DockerInternal
    ports:
      - 8080:8080
      - 8081:8081
    restart: unless-stopped
    
  calibre-web:
    image: linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - /docker/calibre-web/config:/config
      - /mnt/nas/Library/Books:/books
      - "/docker/calibre/Calibre\ Library/:/library"
    network_mode: DockerInternal
    ports:
      - 8083:8083
    restart: unless-stopped
