# docker-compose.yml

version: '3'
services:
  server:
    image: guacozy/guacozy-server
    restart: always
    depends_on:
      - db
    environment:
      - DJANGO_SECRET_KEY=abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz
      - FIELD_ENCRYPTION_KEY=qjq4ObsXMqiqQyfKgD-jjEGm4ep8RaHKGRg4ohGCi1A=
      - DJANGO_DB_URL=postgres://postgres@db:5432/postgres
      - DJANGO_ALLOWED_HOSTS=*
    labels:
      - traefik.enable=true
      - traefik.http.routers.guac.rule=Host(`guac.tuckeredoutbert.com`)  
      - traefik.http.routers.guac.entrypoints=web-secure
      - traefik.http.routers.guac.tls.certresolver=lets-encrypt
      - traefik.docker.network=DockerExternal
    networks:
      - DockerInternal
      - DockerExternal
    #ports:
    #  - 10080:80
    #  - 10443:443
    #volumes:
    #  - /docker/ssh/acme:/ssl
  guacd:
    image: guacamole/guacd
    restart: always
    networks:
      - DockerInternal
  db:
    image: postgres:10.4-alpine
    restart: always
    networks:
      - DockerInternal
    volumes:
    - /docker/guacozy/db:/var/lib/postgresql/data

networks:
  DockerInternal:
    external: true
  DockerExternal:
    external: true
