# docker-compose.yml

version: '3'
services:
  deluge:
    image: lscr.io/linuxserver/deluge:amd64-2.0.5-0202202181752ubuntu20.04.1-ls140
    container_name: deluge
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        - max-file: 5
        - max-size: 1m
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - UMASK_SET=022 #Optional
      - DELUGE_LOGLEVEL=error #Optional
    network_mode: DockerInternal
    ports:
      - 8112:8112
    volumes:
      - /docker/deluge/config:/config
      - /mnt/nas/Downloads/deluge:/downloads
      - /mnt/nas/Downloads/torrents:/torrents
      - /mnt/nas/Downloads/Complete:/complete
