version: '3'
services:
  nzbget:
    image: ghcr.io/linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /docker/nzbget/config:/config
      - /mnt/nas/Downloads/nzb/:/downloads
    network_mode: DockerInternal
    ports:
      - 16789:16789
    restart: unless-stopped 
