version: "3.5"
services:
  unifi-controller:
    network_mode: host
    image: linuxserver/unifi-controller
    container_name: unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=1024M #optional
    volumes:
      - /docker/unifi/config:/config
      - /docker/ssh/acme:/unifi/cert
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8081:8081
      - 8443:8443
      - 8843:8843
      - 8880:8880
      - 6789:6789
    restart: unless-stopped
#    networks:
#      - unifi

#networks:
#  unifi:
#    external: true

