services:
  viseron:
    image: roflcoopter/viseron:latest
    container_name: viseron
    shm_size: "1024mb"
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 1m
    volumes:
      - /mnt/nas/bk/rec:/recordings
      - /mnt/nas/bk/rec/segments:/segments
      - /mnt/nas/bk/rec/snapshots:/snapshots
      - /mnt/nas/bk/rec/thumbnails:/thumbnails
      - /mnt/nas/bk/rec/eventclips:/event_clips
      - /docker/viseron/config:/config
      - /etc/localtime:/etc/localtime:ro
    network_mode: DockerInternal
    restart: unless-stopped
    ports:
      - 8888:8888
      
