services:
  jellyplex-watched:
    image: luigi311/jellyplex-watched:latest
    container_name: jellyplex-watched
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    env_file: "/mnt/nas/bk/jellyplex-watched/.env:./.env"
