services:
  jellyplex-watched:
    image: luigi311/jellyplex-watched:latest
    container_name: jellyplex-watched
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/nas/bk/jellyplex-watched/.env:/app/.env
      - /docker/jellyplex-watched/config:/config
    #env_file: "./.env"
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 1m
    networks:
      DockerInternal:
    restart: unless-stopped

networks:
  DockerInternal:
    external: true
